FW_file: /root/PARFuMS/datasets/FW.fastq
RC_file: /root/PARFuMS/datasets/RC.fastq
BC_file: /root/PARFuMS/examples/barcode_mappingfile.txt
work_dir: /root/PARFuMS/output
primer_file: /root/PARFuMS/datasets/primer.fasta
vector_file: /root/PARFuMS/datasets/vector.fasta
mismatch: true
maxsize: 8000000