FW_file: /root/PARFuMS/datasets/FW.fastq
RC_file: /root/PARFuMS/datasets/RC.fastq
BC_file: /root/PARFuMS/examples/barcode_mappingfile.txt
work_dir: /root/PARFuMS/output
primer_file: /root/PARFuMS/datasets/primer.fasta
vector_file: /root/PARFuMS/datasets/vector.fasta
# 是否输出无barcode匹配的reads
mismatch: true
# 一个样本的最大reads数
maxsize: 8000000
# 运行时的最大进程数
thread: 4
# 自动删除运行过程中产生的临时文件
autodel: false
# info = 0; debug = 1
logger_level: 0